 platform :ios, '13.0'

target 'CartoonGan' do
    use_frameworks!

    pod 'TensorFlowLiteSwift', '~> 2.3.0'
    pod 'SwiftyBeaver'
    pod 'PopupDialog', '~> 1.1'
    pod 'SwiftSpinner'

end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
            end
        end
    end
end
